<?php
session_start();
$sesnama = $_POST["txtNama"];
$sesemail = $_POST["txtEmail"];
$sespesan = $_POST["txtPesan"];
$sesnim = $_POST["txtNim"];
$sesnamalengkap = $_POST["txtNama Lengkap"];
$sestempatlahir = $_POST["txtTempat Lahir"];
$sestanggallahir = $_POST["txtTanggal Lahir"];
$seshobi = $_POST["txtHobi"];
$sespasangan = $_POST["txtPasangan"];
$sespekerjaan = $_POST["txtPekerjaan"];
$sesnamaorangtua = $_POST["txtNama Orang Tua"];
$sesnamakakak = $_POST["txtNama Kakak"];
$sesnamaadik = $_POST["txtNama Adik"];
$_SESSION["sesnama"] = $sesnama;
$_SESSION["sesemail"] = $sesemail;
$_SESSION["sespesan"] = $sespesan;
$_SESSION["sesnim"] = $sesnim;
$_SESSION["sesnamalengkap"] = $sesnamalengkap;
$_SESSION["sestempatlahir"] = $sestempatlahir;
$_SESSION["sestanggallahir"] = $sestanggallahir;
$_SESSION["seshobi"] = $seshobi;
$_SESSION["sespasangan"] = $sespasangan;
$_SESSION["sespekerjaan"] = $sespekerjaan;
$_SESSION["sesnamaorangtua"] = $sesnamaorangtua;
$_SESSION["sesnamakakak"] = $sesnamakakak;
$_SESSION["sesnamaadik"] = $sesnamaadik;
header("location: index.php");
?>